# Generated by Django 2.1.2 on 2018-10-24 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroMascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='EstadoMascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.EstadoMascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='GeneroMascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.GeneroMascota'),
        ),
    ]
