# Generated by Django 2.1.2 on 2018-10-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_raza_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='genero',
        ),
    ]
