# Generated by Django 2.1.2 on 2018-10-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_mascota_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='estado',
        ),
    ]
