# Generated by Django 2.1.2 on 2018-10-24 06:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_mascota_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='EstadoMascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EstadoMascota'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='GeneroMascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GeneroMascota'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='Raza',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='core.Raza'),
            preserve_default=False,
        ),
    ]
